import { useState } from 'react';

interface Report {
  id: string;
  name: string;
  description: string;
  category: string;
  format: string;
  generatedAt: string;
  generatedBy: string;
  fileSize: string;
}

export default function BusinessIntelligenceReports() {
  const [reports] = useState<Report[]>([
    {
      id: '1',
      name: 'Monthly Performance Report - January 2026',
      description: 'Comprehensive monthly performance analysis',
      category: 'Performance',
      format: 'PDF',
      generatedAt: '2026-01-31 23:59',
      generatedBy: 'System',
      fileSize: '2.5 MB',
    },
    {
      id: '2',
      name: 'Revenue Analysis Q4 2025',
      description: 'Quarterly revenue breakdown and trends',
      category: 'Financial',
      format: 'Excel',
      generatedAt: '2026-01-15 10:00',
      generatedBy: 'Finance Team',
      fileSize: '1.8 MB',
    },
    {
      id: '3',
      name: 'Client Retention Report 2025',
      description: 'Annual client retention and satisfaction analysis',
      category: 'Client',
      format: 'PDF',
      generatedAt: '2026-01-10 14:30',
      generatedBy: 'Marketing Team',
      fileSize: '3.2 MB',
    },
    {
      id: '4',
      name: 'Operational Efficiency Report',
      description: 'Analysis of operational metrics and KPIs',
      category: 'Operations',
      format: 'PDF',
      generatedAt: '2026-01-08 09:15',
      generatedBy: 'Operations Team',
      fileSize: '1.5 MB',
    },
  ]);

  const [filterCategory, setFilterCategory] = useState<string>('all');

  const categories = ['Performance', 'Financial', 'Client', 'Operations'];

  const filteredReports = reports.filter(report =>
    filterCategory === 'all' || report.category === filterCategory
  );

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'Performance': return 'bg-blue-100 text-blue-800';
      case 'Financial': return 'bg-green-100 text-green-800';
      case 'Client': return 'bg-purple-100 text-purple-800';
      case 'Operations': return 'bg-orange-100 text-orange-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold mb-2">Business Intelligence Reports</h1>
        <p className="text-gray-600">Generate and access comprehensive business reports</p>
      </div>

      <div className="mb-6 flex gap-4">
        <select
          value={filterCategory}
          onChange={(e) => setFilterCategory(e.target.value)}
          className="px-4 py-2 border rounded-lg"
        >
          <option value="all">All Categories</option>
          {categories.map(cat => (
            <option key={cat} value={cat}>{cat}</option>
          ))}
        </select>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredReports.map((report) => (
          <div key={report.id} className="bg-white rounded-lg shadow p-6">
            <div className="flex justify-between items-start mb-4">
              <div className="flex-1">
                <h3 className="text-lg font-semibold mb-2">{report.name}</h3>
                <p className="text-sm text-gray-600 mb-3">{report.description}</p>
              </div>
              <span className={`px-3 py-1 text-xs font-semibold rounded-full ${getCategoryColor(report.category)}`}>
                {report.category}
              </span>
            </div>

            <div className="space-y-2 text-sm text-gray-600">
              <div className="flex justify-between">
                <span className="font-medium">Format:</span>
                <span>{report.format}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">File Size:</span>
                <span>{report.fileSize}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">Generated At:</span>
                <span>{report.generatedAt}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">Generated By:</span>
                <span>{report.generatedBy}</span>
              </div>
            </div>

            <div className="mt-4 flex gap-2">
              <button className="flex-1 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors">
                Download
              </button>
              <button className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                Preview
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
